# Generated by Django 5.1.4 on 2024-12-06 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(max_length=20),
        ),
    ]
